[package]
name = "mozaic_bot_driver"
version = "0.0.0"
authors = ["Zeus WPI"]

[dependencies]
rand = "0.3.15"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-process = "0.1.1"
futures = "0.1.14"
bytes = "0.4.5"
