[package]
name = "mozaic_bot_driver"
version = "0.0.0"
authors = ["Zeus WPI"]


[lib]
name = "mozaic"
path = "src/lib.rs"

[dependencies]
bytes = "0.4.12"
erased-serde = "0.3"
error-chain = "0.12.1"
futures = "0.1.28"
hex = "0.3.2"
prost = "0.5.0"
prost-derive = "0.5.0"
rand = { version = "0.6.5", default-features = true }
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0"
tokio-timer = "0.2.11"
tokio = "0.1.22"
tokio-core = "0.1.17"
tokio-io = "0.1.12"
tokio-process = "0.2.4"
tokio-codec = "0.1.1"
mozaic-derive = { path = "../mozaic-derive" }
sodiumoxide = "0.2.2"

capnp = "0.10.1"
capnp-futures = "0.10.1"

# for chat example
cursive = "0.13.0"
crossbeam-channel = "0.3.9"

[build-dependencies]
capnpc = "0.10.1"
prost-build = "0.4.0"
mozaic-build = { path = "../mozaic-build" }
